export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const FETCH_PARENT_PROFILE = "FETCH_PARENT_PROFILE";
export const UPDATE_PARENT_WALLET = "UPDATE_PARENT_WALLET";
export const UPDATE_STUDENT_LIMIT = "UPDATE_STUDENT_LIMIT";
export const ORDER_HISTORY = "ORDER_HISTORY";